apiVersion: apps/v1
kind: Deployment
metadata:
  name: pimcore-nginx
  namespace: pimcore-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pimcore-nginx
  template:
    metadata:
      labels:
        app: pimcore-nginx
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: pimcore-nginx-config
      containers:
        - name: nginx
          image: nginx:stable-alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
          ports:
            - containerPort: 80
