apiVersion: apps/v1
kind: Deployment
metadata:
  name: pimcore-php
  namespace: pimcore-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pimcore-php
  template:
    metadata:
      labels:
        app: pimcore-php
    spec:
      containers:
        - name: pimcore-php
          image: pimcore-app:local
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/sbin/php-fpm"]
          env:
            - name: PIMCORE_INSTALL_MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pimcore-db-secret
                  key: MYSQL_USER
            - name: PIMCORE_INSTALL_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pimcore-db-secret
                  key: MYSQL_PASSWORD
            - name: PIMCORE_INSTALL_MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: pimcore-db-secret
                  key: MYSQL_DATABASE
            - name: PIMCORE_INSTALL_MYSQL_HOST_SOCKET
              value: pimcore-db
            - name: PIMCORE_INSTALL_MYSQL_PORT
              value: "3306"
          ports:
            - containerPort: 9000
              name: php-fpm
---
apiVersion: v1
kind: Service
metadata:
  name: pimcore-php
  namespace: pimcore-dev
spec:
  selector:
    app: pimcore-php
  ports:
    - name: php-fpm
      port: 9000
      targetPort: 9000
