apiVersion: v1
kind: Secret
metadata:
  name: pimcore-db-secret
  namespace: pimcore-dev
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ROOT
  MYSQL_DATABASE: pimcore
  MYSQL_USER: pimcore
  MYSQL_PASSWORD: pimcore